// ADHAN MAX DISPLAY DURATION IN SECONDS
export const AZAN_MAX_DURATION_SEC = 180;

// STANDING TRANSITION DURATION IN SECONDS
export const STANDING_DURATION_SEC = 30;

// TOTAL PRAYER SILENCE DURATION FROM IQAMA IN SECONDS
export const PRAYER_WINDOW_SEC = 480;

// TOTAL SILENCE DURATION IN SECONDS
export const SILENCE_DURATION_SEC = PRAYER_WINDOW_SEC - STANDING_DURATION_SEC;
